use_frameworks!

platform :ios, '8.0'

target 'KYModule_Example' do
  pod 'KYModule', :path => '../'

  target 'KYModule_Tests' do
    inherit! :search_paths

    
  end
end



post_install do |install_representation|
  install_representation.pods_project.targets.each do |target|
    if target.name == 'KYModule'
      target.build_configurations.each do |config|
        puts 'config:' + config.name
        if config.name == 'Debug'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)','KYLogModeRelease=0']
          else
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)','KYLogModeRelease=1']
        end
      end
    end
  end
end
